### ISSUE TITLE
How to deploy rl in go2 real robot?

### ISSUE THREAD

**Issue by zhangOSK** [unitreerobotics/unitree_rl_gym#13]
Hi, this repo clearly explained the training and playing process of rl for go2 quadruped. Could you please add information about how to deploy the trained model on real go2 robot?

**Comment by HerocatUED** [comment]
Hi, I've got the same question. Have you solved it yet?

**Comment by sanketlokhande** [comment]
Hi, is this question solved?

**Comment by HerocatUED** [comment]
Hi, I write a simple deploy repo with unitree_sdk2_python. But currently
it's hard to handle sim2real gap.

**Comment by yang-zj1026** [comment]
This [repo](https://github.com/Teddy-Liao/walk-these-ways-go2) might be helpful for go2 real robot deployment

**Comment by heartInsert** [comment]
Go2 is your flagship product, why isn't there even a proper  official  deployment tutorial?

**Comment by WLK8899** [comment]
I hope the official can come up with a framework to deploy the GO2 robot dog

**Comment by IntrovertInDisguise** [comment]
There is nothing compatible with windows

**Comment by iui-whgi** [comment]
unitree please..

**Comment by liuqi8827** [comment]
I hope the official can come up with a framework to deploy the GO2 robot dog

**Comment by TheoBounac** [comment]
Hi ! You should visit this [Deploy_SimToReal_RL_Go2](https://github.com/TheoBounac/Deploy_SimToReal_RL_Go2/tree/main), we are currently working on it. We deployed trained policies with isaaclab on Go2 !
