### ISSUE TITLE
Isaac Gym is replaced by Isaac Lab now, could you please offer a new version for Isaac Lab?

### ISSUE THREAD

**Issue by shy114514** [unitreerobotics/unitree_rl_gym#16]
There are numerous changes in the ways to operation. So it is not easy to move from the former platform to the new one. Would you please consider rewrite this repo?
The note on the website is as follows.
Note: This is legacy software. Developers may download and continue to use it, but it is no longer supported. Please consider using [Isaac Lab](https://developer.nvidia.com/isaac/sim#isaac-lab), an open-source lightweight and performance optimized application for robot learning built on the Isaac Sim platform.

**Comment by craipy-hub** [comment]
Isaaclab has officially provided training for g1, h1, go2. Please visit Isaaclab for more information
[https://isaac-sim.github.io/IsaacLab/main/source/overview/environments.html](https://isaac-sim.github.io/IsaacLab/main/source/overview/environments.html)
