### ISSUE TITLE
can g1's training code be updated, since the urdf has been changed a lot

### ISSUE THREAD

**Issue by melodyhappy** [unitreerobotics/unitree_rl_gym#17]
SOS.I have made many experiments on g1, and found that using newest urdf is hard to train, and permances degraded largely. This
issue really confused me, I really need you help! Thx a lot!

**Comment by craipy-hub** [comment]
The g1 model and training have been updated in the latest commit https://github.com/unitreerobotics/unitree_rl_gym/commit/bd00c6a2a175613eb0599ac796c4240e4ffc527d
