### ISSUE TITLE
How to deploy rl in h1 real robot?

### ISSUE THREAD

**Issue by ZhaoRongfeng** [unitreerobotics/unitree_rl_gym#18]

**Comment by craipy-hub** [comment]
The latest version now supports deployment of G1, H1, and H1_2 on physical robot.

**Comment by myoooofall** [comment]
> The latest version now supports deployment of G1, H1, and H1_2 on physical robot.

so the project not supports Go2 ? so sad ,why all humanoid is supported while no qudrauped
