### ISSUE TITLE
ValueError: Task with name: h1 was not registered

### ISSUE THREAD

**Issue by fanyahao1** [unitreerobotics/unitree_rl_gym#2]
你好，我在用命令行`python legged_gym/scripts/train.py --task=h1 --headless`运行[rl示例程序](https://support.unitree.com/home/zh/developer/rl_example)时出现了以下错误：
```
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 22, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 15, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/root/parkour/legged_gym/legged_gym/utils/task_registry.py", line 89, in make_env
    raise ValueError(f"Task with name: {name} was not registered")
ValueError: Task with name: h1 was not registered
```
在用命令行`python legged_gym/scripts/train.py --task=go2 --headless`运行时是没有问题的。

我查询了__init__.py，发现go2和h1都进行了task_registry，请问这是什么原因？

**Comment by yaocj97** [comment]
请问你是怎么解决的，我在另一个repo碰到了类似的问题

**Comment by fanyahao1** [comment]
可能运行train.py或play.py脚本的目录位置会影响脚本执行。
另外需要修改 legged_gym/scripts/train.py ， legged_gym/scripts/play.py 中的sys.path.append("/home/unitree/go2/legged_gym")为自己的路径。



在 2024-05-07 11:47:45，"yaocj97" ***@***.***> 写道：

请问你是怎么解决的，我在另一个repo碰到了类似的问题
