### ISSUE TITLE
Iteration Numer to train a go2

### ISSUE THREAD

**Issue by Jihy** [unitreerobotics/unitree_rl_gym#22]
I'm wondering how many iterations are needed to train a go2, by using python legged_gym/scripts/train.py --task=go2 --num_envs=1

**Comment by craipy-hub** [comment]
only one envs,you can't get a good policy

**Comment by Jihy** [comment]
What should I do if I just want one go2 running? I noticed that if I set num_envs as N, the obsevation and action would be  N times the size

**Comment by craipy-hub** [comment]
Generally speaking, if the number of environments is less than 2048, the training effect is not good. It is recommended to use 4096 environments. The number of environments N is in the batch dimension and will not affect the dimensions of action and observation; the corresponding action dimension is (N, num_action). When you deploy, the batch dimension can be 1. The batch dimension and action dimension are independent.

**Comment by Jihy** [comment]
Got it, Thanks a lot!

**Comment by hao-xiaoxing** [comment]
> only one envs,you can't get a good policy
How can I train with multiple envs?
