### ISSUE TITLE
failed to add task 

### ISSUE THREAD

**Issue by kight71** [unitreerobotics/unitree_rl_gym#23]
when I run python3  train.py --task=go2 i, it failed and has a RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

how should I solve it

**Comment by craipy-hub** [comment]
It seems to be related to your GPU driver

**Comment by kight71** [comment]
> It seems to be related to your GPU driver

which driver is recommended for training

**Comment by craipy-hub** [comment]
What is your system and graphics card?

**Comment by kight71** [comment]
> What is your system and graphics card?

I ran this project in Ubnuntu and graphics card is RTX4060(laptop)

**Comment by craipy-hub** [comment]
This article may be helpful to you:[isaac-gym-3090-issues]( https://forums.developer.nvidia.com/t/isaac-gym-3090-issues/159080)

**Comment by kight71** [comment]
> This article may be helpful to you:[isaac-gym-3090-issues](https://forums.developer.nvidia.com/t/isaac-gym-3090-issues/159080)

I tried this one. However, ninja failed when I add task. I found that this error need a lower edition of pytorch. To be specific, 1.5.0 below is recommended. But this is conflicted  with the solution above. This solution update the pytorch to the newest edition
