### ISSUE TITLE
What does max_cmd mean in h1 depoly_real script?

### ISSUE THREAD

**Issue by weiyunfei** [unitreerobotics/unitree_rl_gym#30]
Hi, thanks for releasing deployment code for your robots.

I'm confused about the max_cmd in `h1.yaml`, it seems used here. https://github.com/unitreerobotics/unitree_rl_gym/blob/757b05158058a2a8005810c2bb2e1e8667cf3f17/deploy/deploy_real/deploy_real.py#L191

Why it is used as a coefficient like cmd_scale? Is it just a bug?

**Comment by craipy-hub** [comment]
Max_cmd refers to the maximum speed at which the joystick is pushed
