### ISSUE TITLE
ValueError: Task with name: h1 was not registered

### ISSUE THREAD

**Issue by 1hyq1** [unitreerobotics/unitree_rl_gym#7]
python train.py --task=h1
Importing module 'gym_37' (/home/yq/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/yq/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/yq/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/yq/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
Emitting ninja build file /home/yq/.cache/torch_extensions/py37_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    train(args)
  File "train.py", line 13, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/yq/legged_gym/legged_gym/utils/task_registry.py", line 87, in make_env
    raise ValueError(f"Task with name: {name} was not registered")
ValueError: Task with name: h1 was not registered

**Comment by craipy-hub** [comment]
Please try the latest repository code
